import PocketBase from "pocketbase";

const pb = new PocketBase("https://yubi.alwaysdata.net/");

// Données extraites de Ressource_orga.csv (123 enregistrements)
const dataList = [
  {
    code: "R101",
    name: "Anglais",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R102",
    name: "Anglais / anglais renforcé",
    nb_heures_PPN: 10.0,
    nb_heures_semaine: 10.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R103",
    name: "Ergonomie & Accessibilité",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R104",
    name: "Culture numérique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R105",
    name: "Stratégies de communication et marketing",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz", "iigajcomws2d9ld"],
  },
  {
    code: "R106",
    name: "Expression, communication et rhétorique",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik"],
  },
  {
    code: "R107",
    name: "Écriture multimédia et narration",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R108",
    name: "Production graphique",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R109",
    name: "Culture artistique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R110",
    name: "Production audio & vidéo",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R111",
    name: "Intégration",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R112",
    name: "Développement web",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R113",
    name: "Hébergement",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R114",
    name: "Représentation et traitement de l'information",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R115",
    name: "Gestion de projet",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "R116",
    name: "Economie et Droit du numérique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R117",
    name: "PPP",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "SAE101",
    name: "Auditer une communication numérique",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "SAE",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "SAE102",
    name: "Concevoir une recommandation de communication numérique",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "SAE",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "SAE103",
    name: "Produire les éléments d'une communication visuelle",
    nb_heures_PPN: 22.5,
    nb_heures_semaine: 22.5,
    type: "SAE",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "SAE104",
    name: "Réaliser une production audio et vidéo",
    nb_heures_PPN: 22.5,
    nb_heures_semaine: 22.5,
    type: "SAE",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "SAE105",
    name: "Produire un site Web",
    nb_heures_PPN: 55.0,
    nb_heures_semaine: 55.0,
    type: "SAE",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "SAE106",
    name: "Gérer un projet de communication numérique",
    nb_heures_PPN: 45.0,
    nb_heures_semaine: 45.0,
    type: "SAE",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "R201",
    name: "Anglais",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R202",
    name: "Anglais / anglais renforcé",
    nb_heures_PPN: 10.0,
    nb_heures_semaine: 10.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R203",
    name: "Ergonomie & Accessibilité",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R204",
    name: "Culture numérique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R205",
    name: "Stratégies de communication et marketing",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz", "iigajcomws2d9ld"],
  },
  {
    code: "R206",
    name: "Expression, communication et rhétorique",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik"],
  },
  {
    code: "R207",
    name: "Conception graphique et multimédia",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R208",
    name: "Production graphique",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R209",
    name: "Culture artistique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R210",
    name: "Production audio et vidéo",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R211",
    name: "Gestion de contenu",
    nb_heures_PPN: 10.0,
    nb_heures_semaine: 10.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R212",
    name: "Intégration",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R213",
    name: "Développement web",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R214",
    name: "Système d'information",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R215",
    name: "Hébergement",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R216",
    name: "Représentation et traitement de l'information",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R217",
    name: "Gestion de projet",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "R218",
    name: "Economie et Droit du numérique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R219",
    name: "PPP",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "SAE201",
    name: "Exploration des usages",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "SAE",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "SAE202",
    name: "Conception d'un produit ou d'un service et sa communication",
    nb_heures_PPN: 105.0,
    nb_heures_semaine: 105.0,
    type: "SAE",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "SAE203",
    name: "Concevoir un site web avec une source de données",
    nb_heures_PPN: 50.0,
    nb_heures_semaine: 50.0,
    type: "SAE",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "SAE204",
    name: "Construire sa présence en ligne",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "SAE",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "S2 Portfolio",
    name: "Portfolio",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "SAE",
    competences: [
      "szy17ug4fua81xz",
      "iigajcomws2d9ld",
      "nlbvjuwpds4y1uy",
      "wm200e26utyjyk5",
      "dfqxt612fm54xik",
    ],
  },
  {
    code: "R301",
    name: "Anglais",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R302",
    name: "Anglais / anglais renforcé",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R303",
    name: "Design d’expérience",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R304",
    name: "Culture numérique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R305",
    name: "Stratégie de communication et marketing",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "R306",
    name: "Référencement",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "R307",
    name: "Expression, communication et réthorique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik"],
  },
  {
    code: "R308",
    name: "Écriture multimédia et narration",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R309",
    name: "Création et design interactif (UI)",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R310",
    name: "Culture artistique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R311",
    name: "Audiovisuel et motion design",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R312",
    name: "Développement Front et intégration",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R313",
    name: "Dev back (dev) / Gestion de contenus (non dev)",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R314",
    name: "Déploiement de services",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R315",
    name: "Représentation et traitement de l’information",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R316",
    name: "Gestion de projet",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "R317",
    name: "Economie, gestion et droit du numérique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R318",
    name: "PPP",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "SAE301",
    name: "Intégrer des interfaces utilisateurs au sein d'un système d'information",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "SAE",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "SAE302",
    name: "Produire des contenus pour une communication plurimédia",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "SAE",
    competences: ["iigajcomws2d9ld", "nlbvjuwpds4y1uy"],
  },
  {
    code: "SAE303",
    name: "Concevoir des visualisations de données pour le web et un support animé",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "SAE",
    competences: ["wm200e26utyjyk5", "dfqxt612fm54xik"],
  },
  {
    code: "R401",
    name: "Anglais",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R402",
    name: "Économie, gestion et droit du numérique",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R403",
    name: "Design d'expérience",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["szy17ug4fua81xz"],
  },
  {
    code: "R404",
    name: "Expression, communication",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik"],
  },
  {
    code: "R405 Crea",
    name: "Gestion de contenus spécialisée",
    nb_heures_PPN: 45.0,
    nb_heures_semaine: 45.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "R406 Crea",
    name: "Culture artistique",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R407 Crea",
    name: "Audiovisuel   Motion design",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R408 Crea",
    name: "Ecriture multimédia et narration",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R405 Dev",
    name: "Création et design interactif",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R406 Dev",
    name: "Développement front",
    nb_heures_PPN: 40.0,
    nb_heures_semaine: 40.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R407 Dev",
    name: "Développement back",
    nb_heures_PPN: 40.0,
    nb_heures_semaine: 40.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R408 Dev",
    name: "Déploiement de services",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R405 Strat UX",
    name: "Stratégie de Com / Webmarketing",
    nb_heures_PPN: 45.0,
    nb_heures_semaine: 45.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "R406 Strat UX",
    name: "Storytelling (communication narrative)",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R407 Strat UX",
    name: "Gestion de contenus spécialisée",
    nb_heures_PPN: 30.0,
    nb_heures_semaine: 30.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "SAE401 Crea",
    name: "Créer pour une campagne de communication visuelle",
    nb_heures_PPN: 40.0,
    nb_heures_semaine: 40.0,
    type: "SAE",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "SAE401 Dev",
    name: "Développer pour le Web",
    nb_heures_PPN: 60.0,
    nb_heures_semaine: 60.0,
    type: "SAE",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "SAE401 Strat UX",
    name: "Mettre en place une solution ecommerce et la stratégie associée",
    nb_heures_PPN: 50.0,
    nb_heures_semaine: 50.0,
    type: "SAE",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "SAE402 Crea",
    name: "Produire du contenu multimédia",
    nb_heures_PPN: 45.0,
    nb_heures_semaine: 45.0,
    type: "SAE",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "SAE402 Dev",
    name: "Concevoir un dispositif interactif",
    nb_heures_PPN: 25.0,
    nb_heures_semaine: 25.0,
    type: "SAE",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "SAE402 Strat Ux",
    name: "Développer une communication sur les médias sociaux",
    nb_heures_PPN: 35.0,
    nb_heures_semaine: 35.0,
    type: "SAE",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "S4 Portfolio Créa",
    name: "Portfolio Parcours Création Numérique",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "SAE",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "S4 Portfolio Dev",
    name: "Portfolio Parcours Développement Web et Dispositifs interactifs",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "SAE",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "S4 Portfolio Strat UX",
    name: "Portfolio Parcours Stratégie de communication et design d'expérience",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "SAE",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "S4 Stage Créa",
    name: "Stage Parcours Création Numérique",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "Stage",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "S4 Stage Strat UX",
    name: "Stage Parcours Stratégie de communication et design d'expérience",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "Stage",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "S4 Stage Dev",
    name: "Stage Parcours Développement Web et Dispositifs interactifs",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "Stage",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R501",
    name: "Anglais",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R502",
    name: "Management et Assurance qualité",
    nb_heures_PPN: 10.0,
    nb_heures_semaine: 10.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "R503",
    name: "Entrepreneuriat",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "R504",
    name: "Projet Personnel et Professionnel",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "R505 Créa",
    name: "Définir une direction artistique",
    nb_heures_PPN: 40.0,
    nb_heures_semaine: 40.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R506 Créa",
    name: "Création numérique",
    nb_heures_PPN: 75.0,
    nb_heures_semaine: 75.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R507 Créa",
    name: "Ecriture Multimédia et narration",
    nb_heures_PPN: 75.0,
    nb_heures_semaine: 75.0,
    type: "Ressource",
    competences: ["nlbvjuwpds4y1uy"],
  },
  {
    code: "R505 Dev",
    name: "Développement front avancé",
    nb_heures_PPN: 50.0,
    nb_heures_semaine: 50.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R506 Dev",
    name: "Développement back avancé",
    nb_heures_PPN: 50.0,
    nb_heures_semaine: 50.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R507 Dev",
    name: "Dispositifs interactifs",
    nb_heures_PPN: 50.0,
    nb_heures_semaine: 50.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R508 Dev",
    name: "Hébergement et cybersécurité",
    nb_heures_PPN: 40.0,
    nb_heures_semaine: 40.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5"],
  },
  {
    code: "R505 Strat UX",
    name: "Stratégie de communication",
    nb_heures_PPN: 60.0,
    nb_heures_semaine: 60.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "R506 Strat UX",
    name: "Webmarketing",
    nb_heures_PPN: 65.0,
    nb_heures_semaine: 65.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "R507 Strat UX",
    name: "Design d'expérience",
    nb_heures_PPN: 65.0,
    nb_heures_semaine: 65.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld"],
  },
  {
    code: "SAE501 Créa",
    name: "Créer par/pour le numérique",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "SAE",
    competences: ["dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "SAE501 Dev",
    name: "Développer pour le web ou Concevoir un dispositif interactif",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "SAE",
    competences: ["wm200e26utyjyk5", "dfqxt612fm54xik"],
  },
  {
    code: "SAE501 Strat UX",
    name: "Concevoir et déployer une stratégie de communication et une expérience utilisateur",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "SAE",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik"],
  },
  {
    code: "R601",
    name: "Entrepreneuriat",
    nb_heures_PPN: 15.0,
    nb_heures_semaine: 15.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik"],
  },
  {
    code: "R602 Créa",
    name: "Création numérique interactive",
    nb_heures_PPN: 38.0,
    nb_heures_semaine: 38.0,
    type: "Ressource",
    competences: ["dfqxt612fm54xik", "nlbvjuwpds4y1uy"],
  },
  {
    code: "R602 Dev",
    name: "Développement Web et dispositif interactif",
    nb_heures_PPN: 38.0,
    nb_heures_semaine: 38.0,
    type: "Ressource",
    competences: ["wm200e26utyjyk5", "dfqxt612fm54xik"],
  },
  {
    code: "R602 Strat UX",
    name: "Design d'expérience",
    nb_heures_PPN: 18.0,
    nb_heures_semaine: 18.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik"],
  },
  {
    code: "R603 Strat UX",
    name: "Stratégie de communication pluri média",
    nb_heures_PPN: 20.0,
    nb_heures_semaine: 20.0,
    type: "Ressource",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik"],
  },
  {
    code: "S6 Portfolio Créa",
    name: "Portfolio Parcours Création Numérique",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "Portfolio",
    competences: ["nlbvjuwpds4y1uy", "dfqxt612fm54xik"],
  },
  {
    code: "S6 Portfolio Dev",
    name: "Portfolio Parcours Développement Web et Dispositifs interactifs",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "Portfolio",
    competences: ["wm200e26utyjyk5", "dfqxt612fm54xik"],
  },
  {
    code: "S6 Portfolio Strat UX",
    name: "Portfolio Parcours Stratégie de communication et design d'expérience",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "Portfolio",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik"],
  },
  {
    code: "S6 Stage Créa",
    name: "Stage Parcours Création Numérique",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "Stage",
    competences: ["nlbvjuwpds4y1uy", "dfqxt612fm54xik"],
  },
  {
    code: "S6 Stage Dev",
    name: "Stage Parcours Développement Web et Dispositifs interactifs",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "Stage",
    competences: ["wm200e26utyjyk5", "dfqxt612fm54xik"],
  },
  {
    code: "S6 Stage Strat UX",
    name: "Stage Parcours Stratégie de communication et design d'expérience",
    nb_heures_PPN: 0.0,
    nb_heures_semaine: 0.0,
    type: "Stage",
    competences: ["iigajcomws2d9ld", "dfqxt612fm54xik"],
  },
];

(async () => {
  console.log("Début de l'importation...");
  for (const data of dataList) {
    try {
      // On crée l'enregistrement dans la collection 'Enseignements'
      await pb.collection("Enseignements").create(data);
      console.log(`✅ Créé: ${data.code}`);
    } catch (e) {
      console.error(`❌ Erreur sur ${data.code}:`, e.message);
    }
  }
  console.log("Importation terminée.");
})();
